name: Heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Build, Push and Release a Docker container to Heroku.
      # You may pin to the exact commit or the version.
      # uses: gonuit/heroku-docker-deploy@9ab97585f979857642d66612a2ae4062b3347d53
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        # Name of the heroku application to which the build is to be sent.
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        # The email address associated with your Heroku account.
        email:  ${{ secrets.HEROKU_EMAIL }}
        # Heroku API key associated with provided user's email.
        heroku_api_key:  ${{ secrets.HEROKU_API_KEY }}
          
