name: dotnet-docker-heroku CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2   
    - name: Variables substitution.
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'Chat.Api\appsettings.json'
    - name: Docker build
      run: docker login --username=${{ secrets.HEROKU_EMAIL }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
